### ISSUE TITLE
"+" button adds agenda item even if cancelled

### ISSUE THREAD

**Issue by Grantsuu** [adigitalmonk/agilebard.dev#2]
**Describe the bug**
When clicking on the "+" button a blank agenda item will be added if "Cancel" is clicked on the entry aler.

**To Reproduce**
1. Go to https://agilebard.dev/beta/sessions/agenda and create a new session
2. Click on the "+" button to the right of "Agenda"
3. Click on the "Cancel" button on the "Add a new Agenda Item" alert
4. A blank agenda item is added to the agenda of the user

**Expected behavior**
The expected behavior would be no new item is added when the user cancels out of the input alert.

**Screenshots**
<img width="578" alt="Screenshot 2022-11-08 at 12 24 52 AM" src="https://user-images.githubusercontent.com/11323323/200482090-39d46519-0301-4789-9aa0-3ad371f5cce9.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.0
 - Browser: Chrome
 - Version: Version 107.0.5304.87 (Official Build) (arm64)

**Comment by adigitalmonk** [comment]
Dang, good catch! I wasn't planning to use the native `prompt` long term ... but then I did and never went back to clean up the code. I just pushed a fix for this, thanks!!
