### ISSUE TITLE
Focus/Break buttons toggle timer

### ISSUE THREAD

**Issue by Grantsuu** [adigitalmonk/agilebard.dev#3]
**Is your feature request related to a problem? Please describe.**
I would like it if after clicking one of the buttons which start a timer for the user (Focus/Break buttons) you could click the same button again and toggle the timer off, instead of being locked in.

**Describe the solution you'd like**
I think it would be nice to be able to toggle the button off which would then reset and remove the timer.

**Describe alternatives you've considered**
Possibly there could be a "Cancel" button added to the UI which would achieve the same effect.

**Comment by adigitalmonk** [comment]
Yeah, this actually a pretty good suggestion. I could probably rig something up quick enough. 🤔

**Comment by adigitalmonk** [comment]
I just pushed a change to cycle the buttons, let me know what you think 🥳
